### ISSUE TITLE
create_room() needs to deal with 'count' param not set                        

### ISSUE THREAD

**Issue by binary1230** [magfest/hotel#61]
seeing an error happening due to 'count' param not being set, and we're not handling it.

this code here:
```loops = int(params['count']) if params['count'] else 1```

is supposed to deal with the case where it's not set on the form (normally it's assumed to be 1).  we need to swap param['count'] with something like params.get('count').

At a glance, not sure exactly why this is happening because the count parameter is on that form, here's the GET data coming in (note it doesn't include 'count'):
```
    Request Params:
      thursday: 176673583
      notes: Accessibility room
      sunday: 166955552
      friday: 84680830
      saturday: 62603428
      wednesday: 201278048
      tuesday: 6023855
```

```
    Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 227, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 218, in with_caching
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 242, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 358, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 307, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 96, in returns_json
        return json.dumps(func(*args, **kwargs), cls=serializer).encode('utf-8')
      File "/usr/local/uber/plugins/hotel/hotel/site_sections/hotel_assignments.py", line 49, in create_room
        loops = int(params['count']) if params['count'] else 1
    KeyError: 'count'
```

**Comment by binary1230** [comment]
ok didn't realize the form didn't default to having the value of '1' in the field, and that's why it's coming back as None.

We should probably also make the UI default to having a '1' in this box, which looks like the ```value``` attribute is ignored (according to the angular docs)

Looks like we'd have to do something like change:

```
        $scope.room = {notes: ''};
```
to:
```
        $scope.room = {notes: '', count=1};
```
