### ISSUE TITLE
500 error when double-submitting hotel requests

### ISSUE THREAD

**Issue by binary1230** [magfest/hotel#65]
seeing a few of these in the logs:

```
  psycopg2.IntegrityError: duplicate key value violates unique constraint "hotel_requests_attendee_id_key"
   DETAIL:  Key (attendee_id)=([REMOVED]) already exists.
```

It looks like if someone already has a request in the system (i.e. there is a row in the ```hotel_requests``` table with their attendee ID), then we'll see this error.  I guess the solution here is we need to check for this case before this line in hotel_requests.py and display a message like "request already exists"

```
requests = session.hotel_requests(params, checkgroups=['nights'], restricted=True)
```

full trace (I marked sensitive info with [REMOVED]):

```
2016-11-27 10:25:39,315 [ERROR] uber.server: Exception encountered
    Request: POST /uber/hotel_requests/index HTTP/1.0
    Current admin user is: [non-admin user]
    Request Params:
      attendee_id: [REMOVED]
      unwanted_roommates: 
      csrf_token: [REMOVED]
      special_needs: 
      wanted_roommates: [REMOVED]
      nights: ['201278048', '176673583', '84680830', '62603428', '166955552']
      id: None
    Session Params:
    dict_items([('staffer_id', [REMOVED]'), ('csrf_token', [REMOVED]')])
    Request Headers:
      X-FORWARDED-PROTO: https
      Content-Length: 260
      ACCEPT-ENCODING: gzip, deflate, br
      Content-Type: application/x-www-form-urlencoded
      COOKIE: session_id=[REMOVED]
      ACCEPT-LANGUAGE: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
      ORIGIN: https://super2017.uber.magfest.org
      X-REAL-IP: [REMOVED]
      X-FORWARDED-HOST: super2017.uber.magfest.org
      HOST: super2017.uber.magfest.org
      CONNECTION: close
      X-FORWARDED-FOR: [REMOVED]
      UPGRADE-INSECURE-REQUESTS: 1
      REFERER: https://super2017.uber.magfest.org/uber/hotel_requests/
      USER-AGENT: Mozilla/5.0 (Linux; Android 6.0.1; SM-G900T Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36
      CACHE-CONTROL: max-age=0
      Remote-Addr: 127.0.0.1
      ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Traceback (most recent call last):
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 246, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 362, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 311, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 175, in with_check
        return func(self, *args, **kwargs)
      File "/usr/local/uber/plugins/hotel/hotel/site_sections/hotel_requests.py", line 27, in index
        raise HTTPRedirect('../signups/index?message={}', message)
    uber.utils.HTTPRedirect: (['https://super2017.uber.magfest.org/uber/signups/index?message=Your%20hotel%20room%20request%20has%20been%20submitted.%20%20We%27ll%20let%20you%20know%20whether%20your%20offer%20to%20help%20on%20Wednesday%20/%20Sunday%20is%20accepted%2C%20and%20who%20your%20roommates%20will%20be%2C%20a%20few%20weeks%20after%20the%20deadline.'], 302)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
        cursor.execute(statement, parameters)
    psycopg2.IntegrityError: duplicate key value violates unique constraint "hotel_requests_attendee_id_key"
    DETAIL:  Key (attendee_id)=([REMOVED]) already exists.
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 231, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 222, in with_caching
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 250, in with_session
        session.commit()
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
        self.transaction.commit()
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 392, in commit
        self._prepare_impl()
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
        self.session.flush()
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
        self._flush(objects)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
        transaction.rollback(_capture_exception=True)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
        raise value
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
        flush_context.execute()
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
        rec.execute(self)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
        uow
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
        mapper, table, insert)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 729, in _emit_insert_statements
        execute(statement, multiparams)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
        exc_info
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "hotel_requests_attendee_id_key"
    DETAIL:  Key (attendee_id)=([REMOVED]) already exists.
     [SQL: 'INSERT INTO hotel_requests (id, attendee_id, nights, wanted_roommates, unwanted_roommates, special_needs, approved) VALUES (%(id)s, %(attendee_id)s, %(nights)s, %(wanted_roommates)s, %(unwanted_roommates)s, %(special_needs)s, %(approved)s)'] [parameters: {'unwanted_roommates': '', 'attendee_id': UUID('[REMOVED]'), 'special_needs': '', 'wanted_roommates': '[REMOVED]', 'nights': '201278048,176673583,84680830,62603428,166955552', 'id': UUID('[REMOVED]'), 'approved': False}]```

**Comment by EliAndrewC** [comment]
FWIW, that page is already coded in such a way that when you return to it, the form will show the existing information and allow you to edit the existing record.

Thus, the only two ways this error should be able to occur are:
- if someone either submits the same form twice (e.g. hits the back button or hits submit twice in rapid succession or something) 
- if someone has the form open in two tabs, fills it out and submits it once, then fills it out and submits it again in the second tab

So overall, this does seem work fixing, but is probably a low priority since it shouldn't happen for most people.
